version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    container_name: webserverLaravel
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    links:
      - php
    networks:
      - laravel

  mysql:
    image: mariadb
    container_name: dbLaravel
    restart: unless-stopped
    environment:
      - "MYSQL_ROOT_PASSWORD=admin123%"
      - "MYSQL_USER=laravel"
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_PASSWORD=laravel123"
    ports:
      - "4306:3306"
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpLaravel
    volumes:
      - ./src:/var/www/html
    links:
      - mysql
    ports:
      - "9000:9000"
    networks:
      - laravel

networks:
  laravel:
